Add other dp events, and fix possible infinite digest loop
atais/angular-eonasdan-datetimepicker pull request #28
Opened 2017-06-23 07:41 UTC by CapitanMorgan

Adds the previously unimplemented items from http://eonasdan.github.io/bootstrap-datetimepicker/Events/

Fixes digest loop i mentioned in #26  and by doing so allows for the functionality desired in #26

2017-06-23 09:07 UTC, atais commented
@CapitanMorgan whoa, why the tests failed so badly ?

2017-07-07 04:26 UTC, CapitanMorgan commented
When i check out master locally, it was already broken. So I started about trying to fix it.

2017-07-07 10:14 UTC, atais commented
You are right. So at the time of last commit to master Travis was OK, but actually, now it does not pass.
https://travis-ci.org/atais/angular-eonasdan-datetimepicker/builds/197936266

So I think 1st thing would be to sort this out and later I can think of adding new stuff.

2017-07-07 11:34 UTC, atais commented
I fixed the tests in #29

2017-07-07 11:48 UTC, atais requested changes

2017-07-07 11:48 UTC, atais commented on examples/double.html
> +                         on-change="vm.onChangeDatePickerFrom()"
Please keep the old tests untouched.

1.  All new features are optional, so I believe the old scenarios should work?
2. Please provide NEW tests for new features

2017-07-07 11:48 UTC, atais commented on package.json
> -
Those changes are probably not necessary as well.

2017-07-07 11:48 UTC, atais commented on dist/angular-eonasdan-datetimepicker.js
> +                      return true; // return true for invald scenarios to prevent possible infinite digest loop
what are the _invalid_ scenarios?
and why would you return `true` on `isDateEqual` check when they are **invalid**? 

If properties are not date objects, or whatever is they reason why they can't be checked - I think- this method should return `false`.

2017-07-07 13:58 UTC, atais commented
So ideally I would like you to create a test scenario describing this infinite loop that would fail on current master.
And from there you could create a fix for it and present the whole as a PR.

2020-12-03 17:07 UTC, closed without merging